### PR TITLE
Update FAIR_data_variable_dictionary.md

### PR DESCRIPTION
**Pull request by proccaserra**
@weiguUL @daniwelter thx for starting this and shaping it so quickly.
Please find my edits with the PR.
I was thinking of adding a complement by producing a frictionless data package from the table you created (which i altered a bit to add information about 'variable statistical type'

I have added a section about reporting `missing data`

I have added a conclusion and links to other sections (which I'll need to complete)

thx!

### CODE REVIEW

**Comment by weiguUL** [comment]
Thanks @proccaserra , very valuable revision. I will leave it to @daniwelter for her review and confirm the MR.

**Comment by proccaserra** [comment]
just added a mermaid graph

**Review by daniwelter — APPROVED** [review]
I agree with all of @proccaserra's edits. I'd like to clarify one thing though. When we talk about the variable RDF type, do we mean the ontology ID for the field name or the ontology restriction on the values for this field (eg in the case of `sex`, acceptable ontology mappings must be children of the provided ID)? In DDs I've designed for RedCap, it's always been the latter. If it's the former that's intended here, than I think we need both.

I will merge this branch but could we please clarify @weiguUL and @proccaserra ?

**Comment by weiguUL** [comment]
> I agree with all of @proccaserra's edits. I'd like to clarify one thing though. When we talk about the variable RDF type, do we mean the ontology ID for the field name or the ontology restriction on the values for this field (eg in the case of `sex`, acceptable ontology mappings must be children of the provided ID)? In DDs I've designed for RedCap, it's always been the latter. If it's the former that's intended here, than I think we need both.
> 
> I will merge this branch but could we please clarify @weiguUL and @proccaserra ?

I agree that the value restrictions should follow the ontology parent-child relations, if a variable is mapped to an ontology term

**Comment by proccaserra** [comment]
@weiguUL the rdfType element was indeed referring to assigning an ontology class to the actual variable.

- [x] Ideally, the range of values allowed for a categorical variables should also be (ideally) coming from a controlled terminology and thus assigned an identifier, e.g. a CUI from NCIT as when defined a common data element (CDE).

- [x] We could expand the recipe by providing a frictionless data package (I have yet to do this) and a more advanced example in the form of a RedCap example as you indicates.

- [x] We could even have a TransMART example or a CDISC ODM one.
- [x] We could also ask @JolandaS at theHyve if there is something from ODHSI/OMOP.

**Comment by daniwelter** [comment]
@proccaserra That's what I thought. I will update the table with types for all fields and an ontology mapping example for data values.

**Pull request merged**
