### PR TITLE
Update identifiers.md

### PR DESCRIPTION
**Pull request by proccaserra**
Contribution to include discussions with Andrea Splendiani and initial draft document + reorganisation 
General reorganisation 
Addition of conclusion + link to relevant reading material
Addition of Mermaid figure to complement the expanded Abstract/Main Goal section
Addition of Bibliographic reference
Integration of initial draft.

### CODE REVIEW

**Comment by robertgiessmann** [comment]
hi @proccaserra ,

on this:

>  URI construction URI construction is fundamentally about scoping the authority.
   >for example, should the web address be:
        > http://organization/people/1123 
        > or
        > http://organization/commercial/people/1123


--> I would say you usually would rather like to scope via http://commercial.organization/people/1123 , no?

**Comment by robertgiessmann** [comment]
@proccaserra , generally I see a conflict arising here about "target audience". Who is target audience? Your proposal focuses on a rather technology-affine person, while the former version was more general-knowledge-person focused (though still quite technical). 

Shall we create multiple recipes thus?

**Comment by egonw** [comment]
Just a quick ping. I have not lost track of this issue, but still struggling with more urgent deadlines.

**Comment by proccaserra** [comment]
@robertgiessmann: are you saying we should to craft recipes on the same theme for different audiences?
I would prefer to have recipes which are meaningful to most audiences, with general information, but also can go into the specifics, with some technical information, with implementation examples.
Styling could be used to hide the technical bits if these are deemed too much for a less technically-inclined readership
We can probably add a 'TL,DR' section/Take home message section" for the 'manager' audience (the table of content already provides an overview).

Another concern I have with creating multiple recipes on the same topic but for different audiences is how to fit this in the Jupyter-book Table of Content (as it does not allow much nesting). 

Open to suggestions.

**Comment by robertgiessmann** [comment]
Hi @procasserra, yes, that is what I am saying. You’re right about the possibility with expandable sections (which should be collapsed then in the beginning). In the end it’s about that we need to get our target audience decided and fixed. I cannot resolve this right now, only flag it. Sorry.

**Comment by robertgiessmann** [comment]
@proccaserra , do you want to merge the changes still?

**Comment by proccaserra** [comment]
stale, changes included in the current release

**Pull request closed without merging**
