### PR TITLE
Adding three recommended libraries installation

### PR DESCRIPTION
**Pull request by DeniseSl22**
- pip install might be required if these libraries have not been setup before
- The 'request' library was missing from the setup.

@egonw / @tabbassidaloii Could you check my suggestions and potentially merge them :)?
Otherwise the example code will not work in Python

### CODE REVIEW

**Comment by DeniseSl22** [comment]
Another issue I just noticed, this line of text including a website link doesn't seem to go anywhere (as in, I cannot find the ' bridgedb_script.py' code, besides the code snippets).

```
We can then simply pass this variable to the to_df method provided in the bridgedb_script.py module (see [Code](https://faircookbook.elixir-europe.org/content/recipes/interoperability/bridgedb-recipe.html?highlight=bridgedb#Code)). This method will extract the response in text form and turn it into a pandas Dataframe with conveniently named columns and structured data.
```

**Comment by tabbassidaloii** [comment]
> Another issue I just noticed, this line of text including a website link doesn't seem to go anywhere (as in, I cannot find the ' bridgedb_script.py' code, besides the code snippets).
> 
> ```
> We can then simply pass this variable to the to_df method provided in the bridgedb_script.py module (see [Code](https://faircookbook.elixir-europe.org/content/recipes/interoperability/bridgedb-recipe.html?highlight=bridgedb#Code)). This method will extract the response in text form and turn it into a pandas Dataframe with conveniently named columns and structured data.
> ```

Thanks @DeniseSl22 , have you already implemented this suggestion? If not, shall we first fix it and then merge the changes?

**Comment by DeniseSl22** [comment]
@tabbassidaloii : no, for the later point I'm making on the bridgedb_script.py, I was wondering if I was overlooking something (obvious), so I didn't include this in the PR yet.

**Comment by tabbassidaloii** [comment]
> @tabbassidaloii : no, for the later point I'm making on the bridgedb_script.py, I was wondering if I was overlooking something (obvious), so I didn't include this in the PR yet.
Okay, then no change on the recipe itself at the end? but only in the python script?

**Comment by DeniseSl22** [comment]
@tabbassidaloii : I've updated the link to the script, and I also found it just now, so it's making a lot more sense: https://github.com/FAIRplus/the-fair-cookbook/blob/9ad9481be32812b2565f9f9f1897642ae26eddff/content/recipes/interoperability/bridgedb/data/bridgedb_script.py

**Review by tabbassidaloii — APPROVED** [review]

**Pull request merged**
