### PR TITLE
Improve id-resolution.md

### PR DESCRIPTION
**Pull request by cthoyt**
1. Fix label for Name-to-Thing (though I admit their website uses many different pluralizations - see https://n2t.net/e/about.html)
2. Add reference for the Bioregistry

### CODE REVIEW

**Comment by egonw** [comment]
Looks good to me.

**Comment by cthoyt** [comment]
I noticed there's actually a second set of text duplicating this text, should I also update that directly too?

**Comment by proccaserra** [comment]
@cthoyt thx again, same issue as with PR #561, please create PR on 'develop' branch, not 'main'

**Comment by cthoyt** [comment]
@proccaserra beat you to it ;)

**Pull request merged**
