### PR TITLE
WIP: Draft Recipes for findability portion of FAIR Project

### PR DESCRIPTION
**Pull request by zjwarnes**
These are draft recipes any and all criticism is encouraged

### CODE REVIEW

**Comment by robertgiessmann** [comment]
hi @zjwarnes , just to clarify: is this an active draft, or ready to get pulled?

**Review by proccaserra — CHANGES_REQUESTED** [review]
- [ ] remove 'FCB053' from {panels_fairplus} section -> copy paste from another recipe
- [ ] main concern: the content of recipe "FindingCompounds" does not feel aligned with the objectives. It does not show much content or is very narrow (for example: why no explanation as to why Figshare has been selected  .

Is this recipe a draft ? Are you simply trying the PR process?

**Comment by egonw** [comment]
> Is this recipe a draft ? Are you simply trying the PR process?

This pull request is work in progress indeed, allowing people (Robert particularly) to see the progress. Thanks to @robertgiessmann to actually marking it as that, which I should have done myself. Sorry about that.

But yes, trying the PR process, and particularly learning what happens on the "gatekeeper" side is actually part of my consideration too.

BTW, we're splitting out the recipes in separate PRs now, to simplify the writing.

**Comment by egonw** [comment]
@zjwarnes, can you please look at the above (two) comments from Philippe, and apply that to your recipes (to the best of your knowledge; we can discuss tonight)?

**Comment by egonw** [comment]
We're going to make one PR for each recipe. First one: https://github.com/FAIRplus/the-fair-cookbook/pull/370

**Pull request closed without merging**
