### PR TITLE
introduces recipe around EUbOPEN scenario

### PR DESCRIPTION
**Pull request by robertgiessmann**

### CODE REVIEW

**Comment by robertgiessmann** [comment]
note: not yet in TOC; identifier is missing.

**Comment by proccaserra** [comment]
@robertgiessmann @weiguUL It seems that it would be make sense to merge the 2 EUbOpen recipes into one. This one would provide the context needed to understand #404. 
another way to say this is that the content in #402 isn't really a recipe.

thoughts?

**Comment by weiguUL** [comment]
fine for me.

**Comment by proccaserra** [comment]
http://w3id.org/faircookbook/FCB067 merges the 2 stubs initially created.

**Pull request closed without merging**
